---
- hosts: 172.31.40.18
  become: yes
  tasks:
   - name: i want to install git on redhat
     yum:
      name: git
      state: present
   - name: i want to install webserver on redhat
     yum:
      name: httpd
      state: present
   - name: i want to start my webservices on redhat
     service:
      name: httpd
      state: started
