---
- hosts: all
  become: yes
  tasks:
   - name: i want to install webserver on ubuntu16
     apt:
      name: "{{webserveronubuntu}}"
      state: present
      when: ansible_os_family=="Debian"
   - name: i want to start webservices on ubuntu16
     service:
      name: "{{webserveronubuntu}}"
      state: started
      when: ansible_os_family=="Debian"
   - name: i want to install webserver on RedHat
     yum:
      name: "{{webserveronredhat}}"
      state: present
      when: ansible_os_family=="RedHat"
   - name: i want to start webservices on RedHat
     service:
      name: "{{webserveronredhat}}"
      state: started
      when: ansible_os_family=="RedHat"
